thethirdtestament/ViewModels/ContactMessage.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TheThirdTestament.ViewModels
{
    public class ContactMessage
    {
        [Required(ErrorMessage = "Please enter your name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please enter email address")]
        [Display(Name = "Email")]
        [RegularExpression(@"^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$", 
            ErrorMessage = "Please enter correct email address")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please enter a subject")]
        public string Subject { get; set; }
        [Required(ErrorMessage = "Please enter a  message")]
        public string Message { get; set; }
    }
}

thethirdtestament/ViewModels/NewsletterRegistration.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TheThirdTestament.ViewModels
{
    public class NewsletterRegistration
    {
        [Required(ErrorMessage = "Please enter your first name")]
        public string Firstname { get; set; }
        [Required(ErrorMessage = "Please enter your last name")]
        public string Lastname { get; set; }
        [Required(ErrorMessage = "Please enter email address")]
        [Display(Name = "Email")]
        [RegularExpression(@"^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$", 
            ErrorMessage = "Please enter correct email address")]
        public string Email { get; set; }
    }
}

thethirdtestament/Controllers/ContactFormSurfaceController.cs
using TheThirdTestament.ViewModels;
using System.Net.Mail;
using System.Web.Mvc;
using Umbraco.Core.Models;
using Umbraco.Web.Mvc;
using reCAPTCHA.MVC;

namespace TheThirdTestament.Controllers
{
    public class ContactFormSurfaceController : SurfaceController
    {
        // GET: ContactFormSurface
        public ActionResult Index()
        {
            return PartialView("contactForm", new ContactMessage());
        }

        [HttpPost]
        [CaptchaValidator]
        public ActionResult HandleFormSubmit(ContactMessage model)
        {

            //if (!captchaValid)
            //{
            //    ModelState.AddModelError("_FORM", "You did not type the verification word correctly. Please try again.");
            //}
            if (!ModelState.IsValid) { return CurrentUmbracoPage(); }

            MailMessage message = new MailMessage();
            message.To.Add("mail@thethirdtestament.info");
            //message.CC.Add("jan@langekaer.dk");
            message.CC.Add("jesarbov@gmail.com");
            message.Subject = "Mail from thethirdtestament.info: " + model.Subject;
            message.From = new MailAddress(model.Email, model.Name);
            message.Body = model.Message;

            using (SmtpClient smtp = new SmtpClient())
            {
                smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtp.UseDefaultCredentials = false;
                smtp.EnableSsl = true;
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 587;
                smtp.Credentials = new System.Net.NetworkCredential("jesarbov@gmail.com", "yapxnkiyjdmgskcj");
                smtp.EnableSsl = true;

                // send mail
                smtp.Send(message);
                TempData["success"] = true;
            }

            IContent msg = Services.ContentService.CreateContent(model.Subject, CurrentPage.Id, "message");
            msg.SetValue("messageName", model.Name);
            msg.SetValue("email", model.Email);
            msg.SetValue("subject", model.Subject);
            msg.SetValue("messageText", model.Message);
         
            Services.ContentService.Save(msg);

            return RedirectToCurrentUmbracoPage();
        }
    }
}

thethirdtestament/Controllers/NewsletterFormSurfaceController.cs
using TheThirdTestament.ViewModels;
using System.Net.Mail;
using System.Web.Mvc;
using Umbraco.Core.Models;
using Umbraco.Web.Mvc;


namespace TheThirdTestament.Controllers
{
    public class NewsletterFormSurfaceController : SurfaceController
    {
        // GET: ContactFormSurface
        public ActionResult Index()
        {
            return PartialView("newsletterForm", new NewsletterRegistration());
        }

        [HttpPost]
        public ActionResult HandleFormSubmit(NewsletterRegistration model)
        {
            if (!ModelState.IsValid) { return CurrentUmbracoPage(); }

            MailMessage message = new MailMessage();
            message.To.Add("mail@thethirdtestament.info");
            //message.Bcc.Add("jan@langekaer.dk");
            message.Bcc.Add("jesarbov@gmail.com");
            message.Subject = "thethirdtestament.info: Newsletter registration";
            message.From = new MailAddress(model.Email, model.Firstname + " " + model.Lastname);
            message.Body = model.Firstname + " " + model.Lastname + ": " + model.Email;

            using (SmtpClient smtp = new SmtpClient())
            {
                smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtp.UseDefaultCredentials = false;
                smtp.EnableSsl = true;
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 587;
                smtp.Credentials = new System.Net.NetworkCredential("jesarbov@gmail.com", "yapxnkiyjdmgskcj");
                smtp.EnableSsl = true;

                // send mail
                smtp.Send(message);
                TempData["success"] = true;
            }

            IContent msg = Services.ContentService.CreateContent(model.Firstname + " " + model.Lastname, CurrentPage.Id, "newsletterRegistration");
            msg.SetValue("firstname", model.Firstname);
            msg.SetValue("lastname", model.Lastname);
            msg.SetValue("email", model.Email);
            
            Services.ContentService.Save(msg);

            return RedirectToCurrentUmbracoPage();
        }
    }
}

thethirdtestament/Views/ArticleItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.ArticleItem>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "Master.cshtml";
}


<div class="row">
    <div class="col-sm-4">       
    </div>
    <div class="col-sm-8">
        <h1>@Model.Name</h1>
        <div class="author">by <span>@Model.Author</span></div>
    </div>
</div>

<div class="row">
    <div class="col-sm-4">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">Other Articles</h3>
                <ul>
                    @foreach (ArticleItem articleItem in Model.Parent.Children.Where(x => x.GetPropertyValue<int>("category") == 121))
                    {
                        <li><a href="@articleItem.Url">@articleItem.Title</a></li>
                    }
                </ul>
                <h3 class="card-title">Other Texts</h3>
                <ul>
                @foreach (ArticleItem articleItem in Model.Parent.Children.Where(x => x.GetPropertyValue<int>("category") != 121))
                {
                    <li><a href="@articleItem.Url">@articleItem.Title</a></li>
                }
                </ul>
            </div>
        </div>
    </div>    
    <div class="col-sm-8 article text-body">

        @if (@Model.Intro != null) {
            @Model.Intro
        }

        @if (@Model.Content != null) {
            @Model.Content
        }


    </div>
</div>

thethirdtestament/Views/ArticlesOverview.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.ArticlesOverview>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "Master.cshtml";
}

<div class="row">
    <div class="col-8">
        <h1>@Model.Title</h1>
        <div>&nbsp;</div>
    </div>
</div>

<div class="row">
    <div class="col-sm-4">
        <h2>Articles</h2>

        @foreach (ArticleItem articleItem in Model.Children.Where(x => x.HasValue("category") && x.GetPropertyValue<int>("category") == 121))
        {
            <div>
                <a href="@articleItem.Url">@articleItem.Title</a>
                <br />
                @articleItem.Appetizer
            </div>
        }
   
    </div>
    <div class="col-sm-4">

        <h2>Other Texts</h2>
        @foreach (ArticleItem articleItem in Model.Children.Where(x => x.GetPropertyValue<int>("category") != 121))
        {
            <div>
                <a href="@articleItem.Url">@articleItem.Title</a>
                <br />
                @articleItem.Appetizer
            </div>
        }

    </div>

    <div class="col-sm-4">
        @Model.Brochures
        @Html.GetGridHtml(Umbraco.AssignedContentItem, "rightPanel")
    </div>
</div>

thethirdtestament/Views/ContactForm.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContactForm>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

<div class="row">
      <div class="col-12">
        <h1 class="contact-form-header">@Model.Title</h1>
    </div>
</div>

<div class="row">
    <div class="col-12 registration-form">
        @Html.Action("Index", "ContactFormSurface")
    </div>
</div>

thethirdtestament/Views/Home.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<Home>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "Master.cshtml";
}

@* the fun starts here *@

<div class="row">
    <div class="col-12">
        <h1> </h1>
        <div>&nbsp;</div>
    </div>
</div>

@Html.GetGridHtml(Model, "mainContent", "bootstrap3")


@*
    Responsonsive GridPage images implemented:
    \Views\Partials\Grid\Editors\Media.cshtml has implementend 4/12 grid

    <div class="col-md-8 column">
        <div class="two-column-frontpage-image">
            <img srcset="@Model.Image.Url?width=320 320w, @Model.Image.Url?width=420 480w, @Model.Image.Url 680w" sizes="(max-width: 320px) 310px, (max-width: 480px) 460px, 600px" src="@Model.Image.Url" alt="The Third Testament" />
        </div>
    </div>*@

thethirdtestament/Views/LiteratureOverview.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<LiteratureOverview>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

thethirdtestament/Views/MacroPartials/contactForm.cshtml
@using reCAPTCHA.MVC
@model TheThirdTestament.ViewModels.ContactMessage
@{
    /**/

    Layout = null;
}
@if (TempData["success"] == null)
{

    using (Html.BeginUmbracoForm("HandleFormSubmit", "ContactFormSurface", new object { }, new { @class = "form-horizontal" }))
    {

        <div class="form-group row">
            @Html.LabelFor(m => m.Name, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-5">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Name" })
                @Html.ValidationMessageFor(m => m.Name)
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(m => m.Email, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-5">
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email address" })
                @Html.ValidationMessageFor(m => m.Email)
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(m => m.Subject, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-5">
                @Html.TextBoxFor(m => m.Subject, new { @class = "form-control", placeholder = "Subject" })
                @Html.ValidationMessageFor(m => m.Subject)
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(m => m.Message, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-5">
                @Html.TextAreaFor(m => m.Message, new { @class = "form-control", rows = "6", placeholder = "Your message" })
                @Html.ValidationMessageFor(m => m.Message)
            </div>
        </div>

        <div class="form-group row">
            @Html.Label(" ", new { @class = "col-sm-2 control-label" })
            <div class="col-sm-5">
                @Html.Recaptcha()
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-5 offset-sm-2">
                <button id="contact-submit" type="submit" class="btn btn-primary input-medium">Send</button>
            </div>
        </div>
    }
}
else
{
    <p>Thank you for contacting us. We’ll be in touch soon!</p>
}

thethirdtestament/Views/MacroPartials/mainMenu.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@*
    This snippet displays a list of links of the pages immediately under the top-most page in the content tree.
    This is the home page for a standard website.
    It also highlights the current active page/section in the navigation with the css class "current".
*@
@{
    //var selection = CurrentPage.Site().Children.Where("Visible");
    var mainMenu = CurrentPage.AncestorOrSelf(1).Children.Where("Visible");
    var root = CurrentPage.Site();
    //var projectDropdown = CurrentPage.Site().Children.Where("DocumentTypeAlias == \"projectsOverview\"").First().Children.Where("Visible").OrderBy("projectTitle");
}
<ul class="navbar-nav">

    <li class="nav-item @(CurrentPage.Name == root.Name ? "current" : null) ">
        <a class="nav-link" href="@root.Url">@root.Name</a>
    </li>
    @foreach (var menuItem in mainMenu)
    {
        if (menuItem.Children().Where("Visible").Count() > 0 && menuItem.Name != "Articles" && menuItem.Name != "Symbols")
        {
            <li class="nav-item dropdown @(menuItem.IsAncestorOrSelf(CurrentPage) ? "current" : null)">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" id="Preview" role="button" aria-haspopup="true" aria-expanded="false" href="@menuItem.Url">@menuItem.Name</a>

                <div class="dropdown-menu" aria-labelledby="Preview">
                    @foreach (var subMenuItem in menuItem.Children())
                    {
                        <a class="nav-link @(menuItem.IsAncestorOrSelf(CurrentPage) ? "current" : null)" href="@subMenuItem.Url">@subMenuItem.Name</a>
                    }

                </div>
            </li>

        }
        else
        {
            <li class="nav-item @(menuItem.IsAncestorOrSelf(CurrentPage) ? "current" : null)">
                <a class="nav-link" href="@menuItem.Url">@menuItem.Name</a>
            </li>
        }
    }
</ul>

thethirdtestament/Views/MacroPartials/newsletterForm.cshtml
@model TheThirdTestament.ViewModels.NewsletterRegistration
@{
                /**/

                Layout = null;
}
@if (TempData["success"] == null)
{
    
    <div class="row">
        <div class="col-sm-2">
        </div>
        <div class="col-sm-8">
            <h2>
                Stay updated on live stream interactive events
            </h2>
            <br />
        </div>
    </div>
           
                
    using (Html.BeginUmbracoForm("HandleFormSubmit", "NewsletterFormSurface", new object { }, new { @class = "form-horizontal" }))
    {

        <div class="form-group row">
            @Html.LabelFor(m => m.Firstname, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-5">
                @Html.TextBoxFor(m => m.Firstname, new { @class = "form-control", placeholder = "Name" })
                @Html.ValidationMessageFor(m => m.Firstname)
            </div>
        </div>
            <div class="form-group row">
            @Html.LabelFor(m => m.Lastname, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-5">
                @Html.TextBoxFor(m => m.Lastname, new { @class = "form-control", placeholder = "Name" })
                @Html.ValidationMessageFor(m => m.Lastname)
            </div>
        </div>
        <div class="form-group row">
            @Html.LabelFor(m => m.Email, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-5">
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email address" })
                @Html.ValidationMessageFor(m => m.Email)
            </div>
        </div>
          
        <div class="form-group row">
            <div class="col-sm-5 offset-sm-2">
                <button id="contact-submit" type="submit" class="btn btn-primary input-medium">Subscribe</button>
            </div>
        </div>
    }
}
else
{
    <p>Thank you for the registration!</p>
}

thethirdtestament/Views/Master.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = null;
    var logo = Umbraco.TypedMedia(Model.Content.GetPropertyValue<int>("logo", recurse: true));
}
<html>
<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-120710694-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-120710694-1');
    </script>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="description" content="@Model.Content.GetPropertyValue("metaDescription", recurse: true)">

    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Roboto" />
    @Styles.Render("~/bundles/style")

    @*<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
        <link href="~/css/style.css" rel="stylesheet" />
        <link href="~/css/RTE.css" rel="stylesheet" />*@


    <title>@Model.Content.GetPropertyValue("metaTitle", recurse: true)</title>

</head>
<body class="site">
    <div class="container main" id="wrap">
        <header class="wrapper clearfix">
            <a id="header" href="\" style="display:block; white-space: nowrap;">
                <div class="row">

                    <div class="col-md-3 col-sm-3" id="logo">
                        @if (logo != null)
                        {
                            <img src="@logo.Url" alt="logo" />
                        }
                    </div>
                    <div class="col-md-6 col-sm-9 center-content">
                        <div id="site-title">@Umbraco.Field("siteTitle", recursive: true)</div>
                        <div id="site-sub-title">@Umbraco.Field("subSiteTitle", recursive: true)</div>

                    </div>
                    <div class="col-md-3">
                    </div>

                </div>
            </a>

            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    @Umbraco.RenderMacro("mainMenu")
                </div><!-- /.navbar-collapse -->

            </nav>
        </header>

        <!-- main content -->
        <div class="main-content">
            @RenderBody()
        </div>



    </div> <!-- /.container -->

    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    @Umbraco.Field("contactInfo", recursive: true)
                </div>
                <div class="col-md-3">
                    @Umbraco.Field("contact", recursive: true)
                </div>
                <div class="col-md-3">
                    @Umbraco.Field("about", recursive: true)
                </div>
                <div class="col-md-3">
                    @Umbraco.Field("follow", recursive: true)
                </div>
            </div>
        </div>
    </footer>
    
    <script src="~/Scripts/jquery-3.0.0.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>

</body>
</html>

thethirdtestament/Views/NewsletterForm.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<NewsletterForm>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}
<div class="row">
      <div class="col-12">
          <h1 class="contact-form-header">@Model.Title sign-up</h1>
    </div>
</div>
<div class="row">
    <div class="col-12 registration-form">
        @* Html.Action("Index", "NewsletterFormSurface") *@

        <!-- Begin Mailchimp Signup Form -->
        <link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
        <style type="text/css">
                 #mc_embed_signup {
                     background: #fff;
                     clear: left;
                     font: 14px Helvetica,Arial,sans-serif;
                 }
                 /* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
            We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
        </style>
        <div id="mc_embed_signup">
            <form action="https://thethirdtestament.us13.list-manage.com/subscribe/post?u=aa7e9cfe6e78c3894cae257f6&amp;id=c501500417" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
                <div id="mc_embed_signup_scroll">
                    <div class="mc-field-group">
                        <label for="mce-EMAIL">Email Address </label>
                        <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
                    </div>
                    <div id="mce-responses" class="clear">
                        <div class="response" id="mce-error-response" style="display:none"></div>
                        <div class="response" id="mce-success-response" style="display:none"></div>
                    </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_aa7e9cfe6e78c3894cae257f6_c501500417" tabindex="-1" value=""></div>
                    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
                </div>
            </form>
        </div>
        <script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script>
        <script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
        <!--End mc_embed_signup-->

    </div>
</div>

thethirdtestament/Views/NewsletterRegistration.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<NewsletterForm>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

thethirdtestament/Views/Partials/Grid/Bootstrap2-Fluid.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container-fluid">
                <div class="row-fluid clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container-fluid'>")
        <div class="row-fluid clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

thethirdtestament/Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

thethirdtestament/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates


<div class="video-wrapper">
	@Html.Raw(Model.value)
</div>

thethirdtestament/Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

thethirdtestament/Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Templates

@Html.Raw(TemplateUtilities.ParseInternalLinks(Model.value.ToString()))

thethirdtestament/Views/Partials/Grid/Editors/Textstring.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.editor.config.markup != null)
{
    string markup = Model.editor.config.markup.ToString();
    var umbracoHelper = new UmbracoHelper(UmbracoContext.Current);
    markup = markup.Replace("#value#", umbracoHelper.ReplaceLineBreaksForHtml(HttpUtility.HtmlEncode(Model.value.ToString())));
    
    if (Model.editor.config.style != null)
    {
        markup = markup.Replace("#style#", Model.editor.config.style.ToString());
    }

    <text>
        @Html.Raw(markup)
    </text>
}
else
{
    <text>
        <div style="@Model.editor.config.style">@Model.value</div>
    </text>
}

thethirdtestament/Views/SimpleGridLayout.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<SimpleGridLayout>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "Master.cshtml";
}

<div class="row" id="simple-grid-page-header">
    <div class="col-12">
        <h1>@Html.Raw(Model.Title.Replace("\\n", "<br />"))</h1>
    </div>
</div>


@Html.GetGridHtml(Model, "mainContent", "bootstrap3")